# Generated by Django 2.1.5 on 2019-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='state_province',
            field=models.CharField(help_text='请正确填写内容', max_length=30, verbose_name='所属省份'),
        ),
    ]
