# Generated by Django 2.1.5 on 2019-03-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0002_auto_20190311_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', '已出版'), ('producing', '待出版'), ('forbidden', '下架')], default='producing', max_length=64),
        ),
    ]
